### ISSUE TITLE
[BUG] Exception when creating kanji cards from selection

### ISSUE THREAD

**Issue by RicBent** [migaku-official/Migaku-Kanji-Addon#103]
[11:07 AM] kooolm#1408: I'm getting this error when trying to create kanji cards from selection, used to work fine before the last update
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-11-18 14:56:45

Caught exception:
Traceback (most recent call last):
  File "C:\Users\xiaomi\AppData\Roaming\Anki2\addons21\Migaku Kanji__init.py", line 166, in <lambda>
    lambda: CreateCardsFromNotesDialog.show_modal(browser.selectedNotes(), browser)
  File "C:\Users\xiaomi\AppData\Roaming\Anki2\addons21\Migaku Kanji\create_cards_from_notes_dialog.py", line 123, in show_modal
    dlg = cls(note_ids, parent)
  File "C:\Users\xiaomi\AppData\Roaming\Anki2\addons21\Migaku Kanji\create_cards_from_notes_dialog.py", line 43, in init__
    Qt.Checked if (field_name in last_checked and last_checked[field_name]) else Qt.Unchecked
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by RicBent** [comment]
Fixed with 4c5ccfdf956076a6b790dc9a1f33b7b6570746a6
