### ISSUE TITLE
[BUG] Can not create new kanji cards or lookup kanji

### ISSUE THREAD

**Issue by nguyenleccss361** [migaku-official/Migaku-Kanji-Addon#145]
Can not do anything except view kanji stats (but can not click any kanji) and open setting

Below is the log:
"Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-06 23:59:12

Caught exception:
Traceback (most recent call last):
  File "C:\1\Japanese\Anki\addons21\1872210448\create_cards_from_notes_dialog.py", line 96, in create_cards
    util.error_msg_on_error(
  File "C:\1\Japanese\Anki\addons21\1872210448\util.py", line 60, in error_msg_on_error
    func(*args, **kwargs)
  File "C:\1\Japanese\Anki\addons21\Migaku Kanji\kanji.py", line 574, in make_cards_from_characters
    add_note_no_hook(aqt.mw.col, note, deck_id)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-44>", line 2, in add_note
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 630, in repl
  File "C:\1\Japanese\Anki\addons21\1872210448\__init__.py", line 161, in note_added
    aqt.mw.migaku_kanji_db.on_note_update(note.id, deck_id, is_new=True)
TypeError: on_note_update() got an unexpected keyword argument 'is_new'"

**Desktop (please complete the following information):**
 - OS and Version: Windows 10 Home, version: 21H1, OS build: 19043.1415
 - Anki Version: 2.1.35

![image](https://user-images.githubusercontent.com/26450450/148494723-c2fc370e-7f44-4bd2-8e67-2653e31d247f.png)

![image](https://user-images.githubusercontent.com/26450450/148494805-d3792857-9906-4e35-9c11-286ef59fa13e.png)

![image](https://user-images.githubusercontent.com/26450450/148494856-58d9d178-ed2d-4332-bb6a-91d9a64ec88a.png)

**Comment by RicBent** [comment]
What version of the add-on are you using?

**Comment by nguyenleccss361** [comment]
Never mind silly me. I forgot to delete the old Kanji god addon, which is named "Migaku Kanji". It conflicts with the new one.

**Comment by RicBent** [comment]
Alright, glad that fixed it!
