### ISSUE TITLE
Confirm functionality on latest versions of Anki and publish release

### ISSUE THREAD

**Issue by MinmoTech** [migaku-official/Migaku-Kanji-Addon#181]
It has to be checked if the add-on works on all 3 platforms with the latest version of Anki.

In particular compatibility with qt5 and qt6 has to be checked and whether arm and intel macs work.

If it works on all platforms, a new release should be published.
https://github.com/migaku-official/Migaku-Kanji-Addon/issues/164 Should also be fixed before the release.

**Comment by MinmoTech** [comment]
Error when automatically adding cards.
Platform:

```
Version ⁨2.1.65 (aa9a734f)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
```

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.3.5-zen1-1-zen-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-06-08 16:43:27
Add-ons possibly involved: ⁨Migaku Kanji GOD⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "/home/work/.var/app/net.ankiweb.Anki/data/Anki2/addons21/Migaku Kanji GOD/kanji_confirm_dialog.py", line 221, in <lambda>
    lambda: cls._show_new_kanji(ct_kanji, parent)
  File "/home/work/.var/app/net.ankiweb.Anki/data/Anki2/addons21/Migaku Kanji GOD/kanji_confirm_dialog.py", line 212, in _show_new_kanji
    cls.instance = cls(parent, ct_kanji)
  File "/home/work/.var/app/net.ankiweb.Anki/data/Anki2/addons21/Migaku Kanji GOD/kanji_confirm_dialog.py", line 146, in __init__
    ct_kmw = KanjiMarkWidget()
  File "/home/work/.var/app/net.ankiweb.Anki/data/Anki2/addons21/Migaku Kanji GOD/kanji_confirm_dialog.py", line 82, in __init__
    self.setResizeMode(QListView.Adjust)
  File "aqt.qt.qt5_compat", line 342, in __getattr__
AttributeError: type object 'QListView' has no attribute 'BrowserLayout'
```
